### ISSUE TITLE
Expose the exit hook for usage

### ISSUE THREAD

**Issue by SecretAgentKen** [Julusian/node-elgato-stream-deck#10]
With the usage of the exit-hook library, the only way I can successfully catch an exit is by using that same library in my code and establishing a hook before requiring your library. This seems hacky. Instead, could you expose a callback or event so that I can do something like lowering the brightness and clearing the deck prior to application exit along with my own cleanup.

**Comment by Julusian** [comment]
I think the appropriate change here would be to either remove the use of exit-hook completely, or make it be opt-in.
I found a similar situation in another library recently, where its exit handlers was causing the process to exit with nothing being logged as to why

**Comment by Julusian** [comment]
I have removed exit-hook in v5.0.0 in the new https://www.npmjs.com/package/@elgato-stream-deck/node package

If the behaviour is wanted, it should be done manually to call `.close()` when exiting
