### ISSUE TITLE
Exception clearing the device buttons

### ISSUE THREAD

**Issue by cristianmadularu** [Julusian/node-elgato-stream-deck#101]
Hi, after upgrading to the latest version (7.0.0) and perfoming the required code updates, I have noticed that trying to call device.clearPanel() or device.clearKey(index), throws "Uncaught DOMException NotAllowedError: Failed to write the feature report.".

I am using a StreamDeck XL. Drawing on the buttons works well (just like before), only the clear is currently failing. 

Any ideas?

Thank you,

**Comment by cristianmadularu** [comment]
I should add that 'resetToLogo()' does work if that helps.

**Comment by Julusian** [comment]
What firmware version are you running? And could you check the last digit of the model number on the rear?

I suspect this is because I discovered that my XL (through nodejs, didnt test webhid) worked with a 'set key to colour' operation in the protocol, rather than sending across a full black image of pixels.
My xl works fine with this in the webhid demo https://julusian.github.io/node-elgato-stream-deck/#

**Comment by cristianmadularu** [comment]
Thank you for your quick reply @Julusian 
Device opened. Serial: A00NA348308VDQ Firmware: 2.01.002

**Comment by cristianmadularu** [comment]
Model 20GAT9902

**Comment by cristianmadularu** [comment]
This functionality worked with the previous version (6.x) of the library :) so i assume this issues is newly introduced.

**Comment by cristianmadularu** [comment]
Also, that demo web page is throwing the same error
![image](https://github.com/user-attachments/assets/be1dd344-c956-433c-b7c2-bd837bb054d0)

**Comment by Julusian** [comment]
Fixed version is publishing now (v7.0.1), should be ready in a few minutes

**Comment by cristianmadularu** [comment]
Wow that was quick! Thank you very much! 🥇

**Comment by cristianmadularu** [comment]
Btw, the npm publish action for the new version seems to have failed.

**Comment by Julusian** [comment]
Good spot, all published now

**Comment by cristianmadularu** [comment]
Perfect, I have just tested it and everything works as intended! 💯 

Thank you again and keep up the great work! 👍
