### ISSUE TITLE
fillPanelBuffer() Promise not actually waiting for image to be transferred before resolving

### ISSUE THREAD

**Issue by jjeff** [Julusian/node-elgato-stream-deck#28]
I need to do a little more research on this. But, in the webHID version at least, the Promise returned from `fillPanelBuffer()` is resolving before the image has actually been transferred to the panel. 

I'm building an Electron app that fills the panel before quitting the app. However, I currently have to put in a timeout in order to ensure that the image has been written.

```JS
async function fillOnQuit(deck, logoImage) {
  await deck.fillPanelBuffer(logoImage, { format: 'rgba' })
  // panel hasn't actually been filled yet
  await new Promise((resolve) => setTimeout(resolve, 1500))
}
```

**Comment by Julusian** [comment]
Good spot. Fixed in v5.1.2
