### ISSUE TITLE
fillPanel wrong size on Mk2?

### ISSUE THREAD

**Issue by vandenbrakel** [Julusian/node-elgato-stream-deck#29]
I'm trying to set the wallpaper like this on my Mk2

`var streamDeck = myStreamDeck;
const bmpImgField = await Jimp.read(path.resolve(__dirname, 'wallpaper.png')).then((img) => {
		return img.resize(myStreamDeck.ICON_SIZE * myStreamDeck.KEY_COLUMNS, myStreamDeck.ICON_SIZE * myStreamDeck.KEY_ROWS)
	})
	const imgField = bmpImgField.bitmap.data
	streamDeck.fillPanel(imgField)`

I'm getting this error: 
(node:35810) UnhandledPromiseRejectionWarning: RangeError: Expected image buffer of length 233280, got length 311040
    at StreamDeckOriginalMK2.fillPanel 

Anything I'm doing wrong?

Thnaks.

**Comment by Julusian** [comment]
Try setting the second parameter to the call to `fillPanel()`
https://github.com/Julusian/node-elgato-stream-deck/blob/4db447ae3a1f7d711c851358949196350fcec88b/packages/node/examples/fill-button-when-pressed-jimp.js#L18

**Comment by vandenbrakel** [comment]
That was fast! And working perfectly now. Thanks for your quick answer.
