### ISSUE TITLE
MK2 open error

### ISSUE THREAD

**Issue by jmorris644** [Julusian/node-elgato-stream-deck#31]
Running on a raspberry pi with the most current nodejs and npm

I am getting the following error:
```
TypeError: cannot open device with path 0001:0002:00
```
The response from lsusb is:
```
Bus 001 Device 002: ID 0fd9:0080 Elgato Systems GmbH Stream Deck MK.2

```
If that helps

**Comment by jmorris644** [comment]
node-elgato-stream-deck sets the device type to libusb which is now incompatible with node-hib. I do not have an original stream deck so I hope I will not run into the packet size issue. I commented out the set device line in the index.js file and it all works now.

**Comment by Julusian** [comment]
The libusb mode should not be the issue here. I can confirm that the MK2 does work in libusb mode on linux with the latest node-hid(2.1.1), I have just tested it myself to confirm.

As suggested in https://github.com/node-hid/node-hid/issues/453, it does sound like the udev rules are not correct
