### ISSUE TITLE
Pedal Support

### ISSUE THREAD

**Issue by blakekrone** [Julusian/node-elgato-stream-deck#36]
Started to look at adding the Pedal to the devices, operates basically the same way just without screens.

`
[  201.613991] usb 1-1.1: New USB device found, idVendor=0fd9, idProduct=0086, bcdDevice= 1.00
[  201.614009] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  201.614023] usb 1-1.1: Product: Stream Deck Pedal
[  201.614036] usb 1-1.1: Manufacturer: Elgato
[  201.614049] usb 1-1.1: SerialNumber: FL51K1A0XXXX
[  201.626846] input: Elgato Stream Deck Pedal as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.1/1-1.1:1.0/0003:0FD9:0086.0004/input/input3
[  201.693874] hid-generic 0003:0FD9:0086.0004: input,hidraw0: USB HID v11.01 Device [Elgato Stream Deck Pedal] on usb-0000:01:00.0-1.1/input0`

Simple adjustment to the udev rules allows it to be detected, new code is 0086. I pulled down a fork, might try to start looking at it but figured I would post up the ID at least in the meantime.

**Comment by Julusian** [comment]
I think I have a pedal on the way, so I have been planning to look at supporting it once it arrives.

Ill try and find some time in the next couple of days to shuffle around the classes in preparation, so that an implementation can be slotted in.

**Comment by Julusian** [comment]
@blakekrone it looks like you have one of these. If I provide you a simple project to run, could you follow some steps and provide the log output of it?
As there aren't any displays or anything to write to this, I expect we should be able to get this mostly or maybe completely implemented without needing the physical hardware

**Comment by blakekrone** [comment]
Yes, feel free to message me on slack as well whenever you want to work on this!

**Comment by phillco** [comment]
Actually just implemented this for a Python library here :) 

https://github.com/abcminiuser/python-elgato-streamdeck/pull/90

**Comment by Julusian** [comment]
@phillco oh great. Are the serialnumber and firmware version functions tested in that pr?
If so then I should be able to easily port the changes to this library

**Comment by phillco** [comment]
Yup! They print out the proper serial number and FW for me.

**Comment by Julusian** [comment]
I have ported this across in v5.4.0-alpha.0
I shall pull that into companion shortly. If anyone could give this a test to verify it works that would be great

**Comment by Julusian** [comment]
This is confirmed to be working
