### ISSUE TITLE
Model number

### ISSUE THREAD

**Issue by cwilling** [Julusian/node-elgato-stream-deck#46]
This is more idle curiosity than a problem ....

My streamdeck XL returns "xl" as it's model. I noticed on the back of the physical device, along with the serial number is a model number `20GAT9901`. A quick scan of the code didn't reveal any model numbers in that format - just original*, mini, xl & pedal.

Is there any way to extract the other form (20GAT9901) programmatically?

**Comment by Julusian** [comment]
I am not aware of a way. Does the streamdeck software show it? If so then we should be able to fetch it from the usb device.

Or it could be added to the code like these properties are:
https://github.com/Julusian/node-elgato-stream-deck/blob/master/packages/core/src/models/xl.ts#L7-L8

**Comment by cwilling** [comment]
I haven't used the streamdeck software so don't know if it's visible there.

I found a machine to install the software on but I can't see any mention of the fancy model number, just the serial number. The software also had facility to update the firmware, so not a complete waste of time :)

The protocol I'm trying to use the streamdeck with expects a numeric value for "productid" so even the fancy number (20GAT9901) wouldn't satisfy that requirement anyway. I think I can combine the vendorId and productId from usb-detection to make up a unique numeric product identifier for each device as it is discovered.
