### ISSUE TITLE
text-generation example

### ISSUE THREAD

**Issue by cwilling** [Julusian/node-elgato-stream-deck#49]
Should the text-generation example be fully working at the moment?

On button presses I see the background image appear & disappear, as well as the "Filling" & "Clearing" terminal output, but no text (button number?) in the button itself.

On linux with nodejs v12.22.12. All the other examples seem to run OK.

chris

**Comment by cwilling** [comment]
False alarm. I just tried it again and it works.

Sorry about the noise.

**Comment by Julusian** [comment]
Sorry, I forgot about this over the weekend.
That is strange, but Im glad its working now
