### ISSUE TITLE
Incompatible with Electron 21 due to V8 Memory Cage?

### ISSUE THREAD

**Issue by matthewdwatkins** [Julusian/node-elgato-stream-deck#57]
Hello! I am getting this error when using this module in Electron 21:

`[22072:0928/013445.372:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.`

I believe it has to do with this change in Electron's code:

https://www.electronjs.org/blog/v8-memory-cage

**Comment by Julusian** [comment]
Yep, this is a known issue with both [node-hid](https://github.com/node-hid/node-hid) and [@julusian/jpeg-turbo](https://github.com/julusian/node-jpeg-turbo)

For now, stick with Electron 20. Ill fix these issues when I can, but if you use any other modules (eg sharp) then you might also be waiting for them to be updated too

**Comment by matthewdwatkins** [comment]
Great, thank you!

**Comment by Julusian** [comment]
Both [node-hid](https://github.com/node-hid/node-hid) and [@julusian/jpeg-turbo](https://github.com/julusian/node-jpeg-turbo) now have electron 21 compatible versions
