### ISSUE TITLE
Device.getStreamDecks fails when another vendor's device is paired

### ISSUE THREAD

**Issue by deleolajide** [Julusian/node-elgato-stream-deck#60]
This code fails because it assumes that the device list is filtered by vendor. This is the case with navigator.hid.requestDevice, but not with navigator.hid.getDevices which returns all paired devices in respect of vendor

https://github.com/Julusian/node-elgato-stream-deck/blob/c1a996eeb5aeccfbc543a9860d88f65b5ec3be64/packages/webhid/src/index.ts#L29

I have currently hacked the code by disabling the exception and returning null instead

````
	const model = DEVICE_MODELS.find((m) => m.productId === browserDevice.productId)
	if (!model) {
		// throw new Error('Stream Deck is of unexpected type.')
		console.warn('Stream Deck is of unexpected type.')
               return;
	}
````

**Comment by Julusian** [comment]
Thanks, this is fixed now in @elgato-stream-deck/webhid@5.7.1
