### ISSUE TITLE
Feature Request: Ability to get the HID path of an existing StreamDeck instance

### ISSUE THREAD

**Issue by mrfigg** [Julusian/node-elgato-stream-deck#65]
As far as I can tell it is currently not possible to get the HID path of an existing StreamDeck instance. Is there a way to do this that I can't find?

If not would it be possible to add an `async function streamDeck.getHidPath(): Promise<string>` method or equivalent?

**Comment by Julusian** [comment]
There isn't currently a way to do this, but it should be possible to do.

Alternatively, https://github.com/libusb/hidapi/pull/432 will allow for retrieving this once opened, but that change has yet to be pulled into node-hid so is not currently available to us

**Comment by Julusian** [comment]
This is in v6.1.0
