### ISSUE TITLE
Only works for Electron <= 20.3.7 due to sandboxing / "memory cages"

### ISSUE THREAD

**Issue by 1358** [Julusian/node-elgato-stream-deck#68]
[Bug]: Electron 21 breaks node-api stability guarantees 
https://github.com/electron/electron/issues/35801

**Comment by Julusian** [comment]
I can confirm that this library does work with electron 21 and later.

Perhaps you need to force it to install a newer version of node-hid, it looks like this library is requesting ^2.1.1, and 2.1.2 is needed to fix compatibility. This is within the range it will install, but not all package managers will update nested dependencies unless you force them to.
If you are using `@julusian/jpeg-turbo` for enhanced performance, you need to be using at least v2.1.0 of that too
