### ISSUE TITLE
New serial number format with 2 additional characters

### ISSUE THREAD

**Issue by uffefrostbox** [Julusian/node-elgato-stream-deck#76]
I came across a stream deck xl 20GAT9902 with serial A00NA32531SFWL which is 14 characters instead of the normal 12 characters.

I think getSerialNumber() in for example "packages/core/src/models/base-gen2.ts" only allows for the old 12 character types?

Thanks for your great work!

<img width="362" alt="Bildschirmfoto 2023-11-30 um 10 57 43" src="https://github.com/Julusian/node-elgato-stream-deck/assets/16022323/a54f1771-c398-4242-a020-ab671fe4ce1a">

**Comment by Julusian** [comment]
This is supported in v6.2.0

It turns out that in I think the XL, they started including the length of the serialnumber as part of the message. This library is now respecting that value
