### ISSUE TITLE
function openStreamDeck - argument devicePath is no longer optional

### ISSUE THREAD

**Issue by djBehen** [Julusian/node-elgato-stream-deck#77]
In version 6.0.0 argument "devicePath" is no longer optional in function "openStreamDeck". If argument excluded in previous versions the first attached stream deck would be used.

If this is intentional, could anyone give an example of how to set a correct path to an attached stream deck?

I'm using node-elegato-stream-deck in an electron application

**Comment by Julusian** [comment]
You can use the `listStreamDecks()` method to get some basic info about all of the connected streamdecks. The path property it provides can be passed to `openStreamDeck`

I appear to have forgotten to update the examples and documentation for the change making `devicePath` be a required parameter. I shall try and do that soon.
