### ISSUE TITLE
Add native .forget() event

### ISSUE THREAD

**Issue by Kivylius** [Julusian/node-elgato-stream-deck#79]
Native HID event have a `.forget` event, that disconect the device complety, allowing the user to connect with a difference device. Here the docs:

https://developer.mozilla.org/en-US/docs/Web/API/HIDDevice/forget

We current have `.close` event, but this event still remember the device and only closes the connection.

---

Alternatively just expose the `.device` var and let users mess with it as so they please.

Hope that makes sense. I can help raise the PR.

**Comment by Julusian** [comment]
This is in v6.1.0
