### ISSUE TITLE
Stream Deck Neo Support

### ISSUE THREAD

**Issue by dtcooper** [Julusian/node-elgato-stream-deck#87]
New product just announced: https://www.elgato.com/us/en/p/stream-deck-neo

Cheers and thanks for the great library! :)

**Comment by Julusian** [comment]
I have one arriving tomorrow, except support to follow shortly after

**Comment by dtcooper** [comment]
Great! Thanks for the follow up. :)

**Comment by Julusian** [comment]
I have this working, but I need to do some more testing of the library before I can release it as I did some refactoring that could have broken other models.

**Comment by Julusian** [comment]
This has now been tested and is released a v6.2.0
