### ISSUE TITLE
Update Linux Directions to Reference use of Dynamic User ACLs

### ISSUE THREAD

**Issue by erin-allison** [Julusian/node-elgato-stream-deck#88]
The directions described to allow access to the Stream Deck devices on Linux are written in a manner specific to how Ubuntu and Debian are configured, with a statically assigned group owning the device nodes. As noted in [the Archwiki page for udev](https://wiki.archlinux.org/title/udev#Allowing_regular_users_to_use_devices), this has been [discouraged by the systemd developers](https://bugzilla.redhat.com/show_bug.cgi?id=815093) and use of the `plugdev` group [is classified as a bug for Archlinux packages](https://bugs.archlinux.org/task/35602).

The recommended solution on machines using systemd (aka most popular distros) is to tag the devices with a special tag "uaccess", which coordinates with systemd-logind to dynamically grant access when the user is logged in. The only caveat here is that access to the system over SSH doesn't apply the ACL, though given the nature of the devices this library interfaces with, I don't see that as a common issue.

Implementing this as an alternative to the currently documented rules would have the rules file looking like this:

```
SUBSYSTEM=="input", GROUP="input", MODE="0660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0084", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0086", MODE="660", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0090", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0084", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0086", MODE="660", TAG+="uaccess"
KERNEL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0090", MODE="660", TAG+="uaccess"
```

**Comment by Julusian** [comment]
I've moved the rules around a bit (into files instead of part of the readme), and included the two versions.
I hate that we have to do this, but in my experience headless environments are not uncommon.
 Streamdecks with a pi make for a great always on control system for things.

**Comment by erin-allison** [comment]
Mmmm good point, I didn't think about a headless control unit. :+1:
