### ISSUE TITLE
`tslib` seems to still be required as dependency

### ISSUE THREAD

**Issue by foxxyz** [Julusian/node-elgato-stream-deck#9]
Even though 3ebd04f seems to have removed the `tslib` dependency, installing the latest release from npm still complains about it being needed:

```
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /some/path/node_modules/elgato-stream-deck/dist/models/index.js
- /some/path/node_modules/elgato-stream-deck/dist/index.js
- /some/path/index.js
```

Looking into it, this seems to be caused by `export *` in [`models/index.ts`](https://github.com/Julusian/node-elgato-stream-deck/blob/master/src/models/index.ts). 

Replacing this line with `export { KeyIndex, DeviceModelId, StreamDeckDeviceInfo } from './id'` would fix this. However, I am no TypeScript expert and there may be a more elegant TS-specific alternative I'm not aware of.

Happy to submit a PR, let me know your preference.

**Comment by Julusian** [comment]
I guess this will be because I completely replaced the tsconfig, so the fix you linked needs to be reapplied.

I'll write a fix and do a new release tomorrow

**Comment by ahmadnassri** [comment]
FYI: it looks like 4.0.1 is not on npm's registry.

**Comment by Julusian** [comment]
I needed to do a little digging before publishing it, as the tests were failing. That looks to be a problem in a different project, so this is now published to npm

**Comment by ahmadnassri** [comment]
thank you :+1:

**Comment by foxxyz** [comment]
Nice! Thanks @Julusian!
