### ISSUE TITLE
run switchToProfile() event

### ISSUE THREAD

**Issue by mircobabini** [Julusian/node-elgato-stream-deck#91]
Is it possible to use this nodejs lib to just run a switchToProfile() command on the streamdeck?
https://docs.elgato.com/sdk/plugins/events-sent#switchtoprofile

**Comment by Julusian** [comment]
As stated in the readme

> This library has nothing to do with the streamdeck software produced by Elgato. There is nothing here to install and run. This is a library to help developers make alternatives to that software

So no, it cannot do that
